import type { Table } from "@tanstack/react-table"
import type { CellUpdate } from "@/types/data-grid"
import type { CellActor } from "@/types/cell-attribution"

type FlatRow = Record<string, unknown>

/**
 * Imperative handle exposing grid APIs for Korra tool calls.
 *
 * DataGridView owns all grid internals; this is the narrow surface
 * that HomeDashboard (and eventually onToolCall) can use to
 * manipulate the table programmatically.
 */
export type ColumnSource = "lookup" | "ai-generated"

export interface AddColumnOptions {
  id: string
  name: string
  type: string
  options?: Array<{ value: string; label: string; color?: string }>
  /** Where this column's data comes from — affects visual treatment */
  source?: ColumnSource
}

export type Attribution = "korra" | "user"

export interface GridHandle {
  /** TanStack Table instance — filters, sorting, selection, row model */
  table: Table<FlatRow>
  /** Update one or more cells by row index + column ID */
  updateCells: (updates: CellUpdate | CellUpdate[]) => void
  /** Delete rows by index */
  deleteRows: (rowIndices: number[]) => void
  /** Add a row with the given field values */
  addRow: (row: FlatRow) => void
  /** Add a new column to the grid */
  addColumn: (options: AddColumnOptions) => void
  /** Replace data + columns (for switching databases) */
  setDataAndColumns: (data: FlatRow[], columns: import("@tanstack/react-table").ColumnDef<FlatRow>[]) => void
  /** Current row data */
  getData: () => FlatRow[]
  /** Switch to an API database by slug */
  openDatabase: (slug: string) => void
  /** Mark filter/sort attribution (who last changed it) */
  setFilterAttribution: (attr: Attribution) => void
  setSortAttribution: (attr: Attribution) => void
  /** Mark a column as being generated by AI (shows shimmer overlay) */
  setGeneratingColumn: (columnId: string, generating: boolean) => void
  /** Record a cell edit for attribution tracking */
  recordCellEdit?: (
    rowId: string,
    columnId: string,
    value: unknown,
    prevValue: unknown,
    actor: CellActor,
    toolCallId?: string,
    context?: string
  ) => void
}
